{{- range $name, $svc := .Values.services }}
{{- if $svc.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "microservices.labels" $ | nindent 4 }}
spec:
  type: {{ $svc.service.type }}
  selector:
    app: {{ $name }}
  ports:
    - name: {{ $svc.service.name }}
      port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.targetPort }}
      protocol: {{ default "TCP" $svc.service.protocol }}
---
{{- end }}
{{- if and (eq $name "frontend") $svc.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  labels:
    app: frontend
    {{- include "microservices.labels" $ | nindent 4 }}
spec:
  type: {{ $svc.externalService.type }}
  selector:
    app: frontend
  ports:
    - name: {{ $svc.externalService.name }}
      port: {{ $svc.externalService.port }}
      targetPort: {{ $svc.externalService.targetPort }}
      protocol: {{ default "TCP" $svc.externalService.protocol }}
---
{{- end }}
{{- end }}
