# Namespace is intentionally not hard-coded here.
# Install with: helm upgrade --install microservices ./microservices-helm -n microservices --create-namespace
ingress:
  enabled: true
  className: traefik

  annotations: {}

  hosts:
    - host: ecommerce-prod.justtrytech.com
      paths:
        - path: /
          pathType: Prefix

  tls: []
  
services:
  emailservice:
    image: prasanna1808/emailservice:latest
    containerPort: 8080
    service:
      enabled: true
      type: ClusterIP
      port: 5000
      targetPort: 8080
      protocol: TCP
      name: grpc
    env:
      PORT: "8080"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      privileged: false
      readOnlyRootFilesystem: true
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    terminationGracePeriodSeconds: 5
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:8080
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:8080
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  checkoutservice:
    image: prasanna1808/checkoutservice:latest
    containerPort: 5050
    service:
      enabled: true
      type: ClusterIP
      port: 5050
      targetPort: 5050
      protocol: TCP
      name: grpc
    env:
      PORT: "5050"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      PAYMENT_SERVICE_ADDR: "paymentservice:50051"
      EMAIL_SERVICE_ADDR: "emailservice:5000"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:5050
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:5050
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  recommendationservice:
    image: prasanna1808/recommendationservice:latest
    containerPort: 8080
    service:
      enabled: true
      type: ClusterIP
      port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
    env:
      PORT: "8080"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 220Mi }
      limits: { cpu: 200m, memory: 450Mi }
    terminationGracePeriodSeconds: 5
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:8080
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:8080
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  frontend:
    image: prasanna1808/frontend:latest
    containerPort: 8080
    service:
      enabled: true
      type: NodePort
      port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    externalService:
      enabled: true
      type: LoadBalancer
      port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    env:
      PORT: "8080"
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
      RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
      AD_SERVICE_ADDR: "adservice:9555"
      ENABLE_PROFILER: "0"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    podAnnotations:
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    readinessProbe:
      httpGet:
        path: /_healthz
        port: 8080
        httpHeaders:
          - name: Cookie
            value: shop_session-id=x-readiness-probe
      initialDelaySeconds: 10
    livenessProbe:
      httpGet:
        path: /_healthz
        port: 8080
        httpHeaders:
          - name: Cookie
            value: shop_session-id=x-liveness-probe
      initialDelaySeconds: 10

  paymentservice:
    image: prasanna1808/paymentservice:latest
    containerPort: 50051
    service:
      enabled: true
      type: ClusterIP
      port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    env:
      PORT: "50051"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    terminationGracePeriodSeconds: 5
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:50051
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:50051
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  productcatalogservice:
    image: prasanna1808/productcatalogservice:latest
    containerPort: 3550
    service:
      enabled: true
      type: ClusterIP
      port: 3550
      targetPort: 3550
      protocol: TCP
      name: grpc
    env:
      PORT: "3550"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:3550
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:3550
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  cartservice:
    image: prasanna1808/cartservice:latest
    containerPort: 7070
    service:
      enabled: true
      type: ClusterIP
      port: 7070
      targetPort: 7070
      protocol: TCP
      name: grpc
    env:
      REDIS_ADDR: "redis-cart:6379"
    resources:
      requests: { cpu: 200m, memory: 64Mi }
      limits: { cpu: 300m, memory: 128Mi }
    terminationGracePeriodSeconds: 5
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:7070
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:7070
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  loadgenerator:
    image: prasanna1808/loadgenerator:latest
    containerPort: null
    service:
      enabled: false
    replicas: 1
    env:
      FRONTEND_ADDR: "frontend:80"
      USERS: "10"
    resources:
      requests: { cpu: 300m, memory: 256Mi }
      limits: { cpu: 500m, memory: 512Mi }
    podAnnotations:
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      privileged: false
      readOnlyRootFilesystem: true
    restartPolicy: Always
    terminationGracePeriodSeconds: 5

  currencyservice:
    image: prasanna1808/currencyservice:latest
    containerPort: 7000
    service:
      enabled: true
      type: ClusterIP
      port: 7000
      targetPort: 7000
      protocol: TCP
      name: grpc
    env:
      PORT: "7000"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:7000
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:7000
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  shippingservice:
    image: prasanna1808/shippingservice:latest
    containerPort: 50051
    service:
      enabled: true
      type: ClusterIP
      port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    env:
      PORT: "50051"
      DISABLE_PROFILER: "1"
    resources:
      requests: { cpu: 100m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:50051
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:50051
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

  redis-cart:
    image: redis:alpine
    containerPort: 6379
    service:
      enabled: true
      type: ClusterIP
      port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp-redis
    env: {}
    resources:
      requests: { cpu: 70m, memory: 200Mi }
      limits: { cpu: 125m, memory: 256Mi }
    readinessProbe:
      tcpSocket:
        port: 6379
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 6379
      periodSeconds: 5
    persistence:
      enabled: false

  adservice:
    image: prasanna1808/adservice:latest
    containerPort: 9555
    service:
      enabled: true
      type: ClusterIP
      port: 9555
      targetPort: 9555
      protocol: TCP
      name: grpc
    env:
      PORT: "9555"
    resources:
      requests: { cpu: 200m, memory: 180Mi }
      limits: { cpu: 300m, memory: 300Mi }
    readinessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:9555
          - -rpc-timeout=5s
      initialDelaySeconds: 15
    livenessProbe:
      exec:
        command:
          - /bin/grpc_health_probe
          - -addr=:9555
          - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10

imagePullSecrets: []
